/*
    QUESTION ::What range of years does the provided database cover?
        ...
    SOURCES :: appearances table
        * ...
    DIMENSIONS :: yearid
        * ...
    FACTS :: Maximum and Minimum years
        * ...
    FILTERS ::
        * ...
    DESCRIPTION :: Searching through appearnaces table where all the games data contained
        ...
    ANSWER :: FROM 1871 TO 2016 
        ...
*/
 
SELECT MIN(yearid) AS start_year, MAX(yearid) AS end_year
FROM appearances;
